### PR TITLE
Fix EZP-32349: do not leave stale data in ezcontentclass_attribute_ml

### PR DESCRIPTION
**Pull request by gggeek**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZP-32349
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.0` to `v3.3`
| **BC breaks**                          | no
| **Doc needed**                       | no

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs). <= no. Which branch is 3.x ?
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`). <= no, as this is reshuffling of existing code
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`) <= is that supposed to be a slack username or what ?

### CODE REVIEW

**Comment by bdunogier** [comment]
The bug looks valid to me. Ping @alongosz / @ezsystems/php-dev-team for review.

**Comment by ViniTou** [comment]
Two things:
- Can we have some tests for it, just to be sure that there would be no regression?
- If it is in ezplatform 2.5 it should target `ezpublish-kernel:7.5`

**Review by ViniTou — COMMENTED** [review]
Two things:

- Can we have some tests for it, just to be sure that there would be no regression?
- If it is in ezplatform 2.5 it should target ezpublish-kernel:7.5

**Comment by gggeek** [comment]
@ViniTou 

1. I can not find a branch named 'ezpublish-kernel:7.5' when trying to modify this PR via the github interface... is that a codename or am I missing something ?
2. as for testing, I am satisfied that this work because it makes the unit tests for eZMigrationBundle2 pass (they fail otherwise). Given that I have not looked into the eZPlatform test stack in a long time, I'd appreciate if it was someone from the core dev team picking up this task...

**Comment by ViniTou** [comment]
@gggeek 
https://github.com/ezsystems/ezpublish-kernel/tree/7.5

**Comment by gggeek** [comment]
Ok, so that's another repo altogether. What is the standard workflow in this case: I send the PR to ezpublish-kernel and then after you merging you push it somehow to ezplatform-kernel? Or do I have to create 2 separate PRs? Or ...?

**Comment by ViniTou** [comment]
>after you merging you push it somehow to ezplatform-kernel?
Yes, this is how we roll with it.

**Comment by gggeek** [comment]
Ok, creating a new PR there then

**Comment by alongosz** [comment]
Closing in favor of ezsystems/ezpublish-kernel#3090

**Pull request closed without merging**
