### PR TITLE
EZP-31795: Added VersionInfo to getThumbnail method in order to utilise builtin caching mechanism

### PR DESCRIPTION
**Pull request by ViniTou**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | EZP-31795
| **Type**                                   | feature
| **Target eZ Platform version** | `v3.3`
| **BC breaks**                          | yes
| **Doc needed**                       | yes

https://github.com/ezsystems/ezplatform-admin-ui/pull/1690
https://github.com/ezsystems/ezplatform-connector-dam/pull/29

#### Checklist:
- [ ] Provided PR description.
- [ ] Tested the solution manually.
- [ ] Provided automated test coverage.
- [ ] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [ ] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [ ] Asked for a review (ping `@ezsystems/php-dev-team`).

### CODE REVIEW

**Comment by alongosz** [comment]
@ViniTou CI is failing. Some description is needed - why passing VersionInfo solves the issue?

**Comment by ViniTou** [comment]
@alongosz 
`VariationHandler` needs proper `VersionInfo` in order to generate cache key, in our implementation dummy `new VersionInfo()` was provided.
`\eZ\Bundle\EzPublishCoreBundle\Imagine\Cache\AliasGeneratorDecorator::getVariation`

**Review by lserwatka — APPROVED** [review]

**Comment by lserwatka** [comment]
@ViniTou Could you investigate CI?

**Review by alongosz — APPROVED** [review]

**Comment by lserwatka** [comment]
@ViniTou rebase is required

**Comment by ViniTou** [comment]
Fixed Unit & integration test, only behat is failing as the signature changes in adminUI implementation (done here https://github.com/ezsystems/ezplatform-admin-ui/pull/1690)

**Review by alongosz — APPROVED** [review]

**Review by micszo — APPROVED** [review]
Verified with sanities on Ibexa Commerce 3.3.0-dev with diffs.

**Pull request merged**
