### PR TITLE
[Fast forward][3.3] Merge up of IBX-819: Shortened persistence cache tags

### PR DESCRIPTION
**Pull request by alongosz**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-819](https://issues.ibexa.co/browse/IBX-819)
| **Type**                                   | improvement
| **Target Ibexa version** | `v3.3`
| **BC breaks**                          | no

This is a merge up of https://github.com/ezsystems/ezpublish-kernel/pull/3114 and an alternative (with proper merge commit) to https://github.com/ezsystems/ezplatform-kernel/pull/229.

#### TODO:
- [x] Fix unit test data provider crashing
- [x] Fix container parameters escaping in test service container
- [x] Test (QA) the changes for v3.3

### CODE REVIEW

**Comment by micszo** [comment]
@alongosz the back office does not work with this branch, deployed with Ibexa Commerce 3.3.8.
`Too few arguments to function eZ\Publish\Core\Persistence\Cache\AbstractHandler::__construct(), 3 passed in /app/vendor/ezsystems/ezplatform-personalization/src/lib/Cache/CachedSettingService.php on line 33 and exactly 4 expected [in vendor/ezsystems/ezplatform-kernel/eZ/Publish/Core/Persistence/Cache/AbstractHandler.php:40]`

Screenshot 2021-09-13 at 15 40 40

**Comment by alongosz** [comment]
@micszo seems there are specific personalization changes on 3.3 which called code that has been changed.
Fixed via https://github.com/ezsystems/ezplatform-personalization/pull/232

@ezsystems/php-dev-team this is a merge up of https://github.com/ezsystems/ezpublish-kernel/pull/3114. If you see some mistakes here, let me know.

**Review by Steveb-p — APPROVED** [review]
I don't see any obvious issues. Static analysis would be great to have :sweat_smile:

**Review by konradoboza — APPROVED** [review]
LGTM 👍  thank you @alongosz!

**Review by micszo — APPROVED** [review]
QA Approved on Ibexa Commerce 3.3.8, relied mostly on platform.sh.

Tested with https://github.com/ezsystems/ezplatform-personalization/pull/232.

**Comment by alongosz** [comment]
Merged via f41927705 with additional changes from 7.5 branch.

**Pull request closed without merging**
