### PR TITLE
[EZP-31773] Remember me support multiple user providers

### PR DESCRIPTION
**Pull request by wizhippo**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31773](https://jira.ez.no/browse/EZP-31773)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.x`
| **BC breaks**                          | no
| **Tests pass**                          | yes/no
| **Doc needed**                       | no

Check first if the token is an ez user else pass it on so the interactive login will do it's job and update the user with a wrapped user.

#### Checklist:
- [x] PR description is updated.
- [x] Added code follows Coding Standards (use `$ composer fix-cs`).
- [x] PR is ready for a review.

### CODE REVIEW

**Comment by wizhippo** [comment]
Any change this will be merged?

**Comment by lserwatka** [comment]
@ezsystems/qa-team we need sanitise here

**Review by bogusez — APPROVED** [review]

**Comment by lserwatka** [comment]
Thank you @wizhippo

**Comment by wizhippo** [comment]
What needs to be done to get this into 1.1.x?

**Comment by lserwatka** [comment]
@alongosz can we cherry-pick this one to 1.1. I will include this one in 3.1.3

**Comment by alongosz** [comment]
Cherry-picked for 3.1 via #111. We need QA on this IMHO.

@wizhippo in the future please make sure that you're targeting appropriate branch. We try to guess your intent, but we're not gonna see it always (esp. that JIRA ticket also says it occurs on master only).
Cherry-picking creates a bit of mess in the history because of git-flow. We've been over this multiple times already AFAIR, BTW ;-)

**Pull request merged**
