### PR TITLE
EZP-31837: Creating an additional Content Location does not respect Content visibility

### PR DESCRIPTION
**Pull request by pspanja**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31837](https://jira.ez.no/browse/EZP-31837)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.1.3`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no

#### Checklist:
- [x] PR description is updated.
- [x] Tests are implemented.
- [x] Added code follows Coding Standards (use `$ composer fix-cs`).
- [x] PR is ready for a review.

### CODE REVIEW

**Review by adamwojs — APPROVED** [review]

**Comment by ViniTou** [comment]
Should it not target `1.1` at least?
@adamwojs

**Comment by adamwojs** [comment]
> Should it not target `1.1` at least?

You are right. AFAIR content hide/reveal was part of the `eZ Platform 2.5` so probably bug is there as well.

**Comment by pspanja** [comment]
OK, do let me know where exactly you want this.

**Comment by lserwatka** [comment]
Could you open this against ezpublish-kernel/7.5 branch. We will run QA on 2.5.x and 3.1.x.

**Comment by pspanja** [comment]
OK, will do. I also added a fix for incorrect docs of `Location::$invisible` property in https://github.com/ezsystems/ezplatform-kernel/pull/107/commits/4acc1d4365ea042492f05bae080e6e0a5056a4e6, as tested here: https://github.com/ezsystems/ezplatform-kernel/blob/2b64f12724c29bfad54438bc6d8fb7ca75d69094/eZ/Publish/API/Repository/Tests/ContentServiceTest.php#L6324

**Comment by lserwatka** [comment]
> OK, will do. I also added a fix for incorrect docs of `Location::$invisible` property in [4acc1d4](https://github.com/ezsystems/ezplatform-kernel/commit/4acc1d4365ea042492f05bae080e6e0a5056a4e6), as tested here:
> 
> https://github.com/ezsystems/ezplatform-kernel/blob/2b64f12724c29bfad54438bc6d8fb7ca75d69094/eZ/Publish/API/Repository/Tests/ContentServiceTest.php#L6324

Looks good. Thank you

**Comment by pspanja** [comment]
Opened https://github.com/ezsystems/ezpublish-kernel/pull/3066

**Comment by adamwojs** [comment]
Closed in favor of ezsystems/ezpublish-kernel#3066 (changes will be merged up)

**Pull request closed without merging**
