### PR TITLE
IBX-300: Added timezone offset to timestamp

### PR DESCRIPTION
**Pull request by mateuszdebinski**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [IBX-300](https://issues.ibexa.co/browse/IBX-300)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.2`
| **BC breaks**                          | no
| **Doc needed**                       | no

Related PR: https://github.com/ezsystems/ezplatform-admin-ui/pull/1752

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Provided automated test coverage.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review (ping `@ezsystems/php-dev-team`).

### CODE REVIEW

**Comment by Steveb-p** [comment]
I've noticed that `Value::fromTimestamp()` method constructs `DateTime` objects by passing timestamps directly into constructor method. Shouldn't this be changed into:
```diff
    public static function fromTimestamp($timestamp)
    {
        try {
-            return new static(new DateTime("@{$timestamp}"));
+            $datetime = new DateTime();
+            $datetime->setTimestamp($timestamp);
+
+            return new static($datetime);
        } catch (Exception $e) {
            throw new InvalidArgumentValue('$timestamp', $timestamp, __CLASS__, $e);
        }
    }
```

Reason for this is that `DateTime` objects created using timestamps passed to constructor are actually initialized with offsets +0000, instead of offsets coming from `date_default_timezone_get`. This means that `DateTime` objects created this way will have potentially different offsets, therefore generating different values for, for example, `DateTime::format` method.

This might be the reason why those datetimes differ in the first place. Adding default offset would cause that an actually invalid timestamp would be stored (!).

**Review by Steveb-p — CHANGES_REQUESTED** [review]
Please address the issue raised in the comment.

**Comment by mateuszdebinski** [comment]
> Please address the issue raised in the comment.

The proposed change actually works as you describe, but then there is a problem on the front side, so I need to verify the JS files that are responsible for it

**Review by alongosz — CHANGES_REQUESTED** [review]
Looks like we're missing test coverage

**Review by Steveb-p — APPROVED** [review]
LGTM. @alongosz do you think we need some more tests for this?

**Review by alongosz — APPROVED** [review]

**Review by konradoboza — APPROVED** [review]

**Comment by Steveb-p** [comment]
One thing to note: do we need to migrate anyone? Can any customer have timestamps stored with an offset?

**Comment by mateuszdebinski** [comment]
> One thing to note: do we need to migrate anyone? Can any customer have timestamps stored with an offset?

I think no, there shouldn't be any incorrect data saved anywhere, because when creating this item we changed the timestamp (add offset timezone) via JS now we do it in PHP

**Review by bogusez — APPROVED** [review]

**Comment by mateuszdebinski** [comment]
merge up - done

**Pull request merged**
