### PR TITLE
On ContentType copy clear the responding persistence cache

### PR DESCRIPTION
**Pull request by MarioBlazek**
| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | [EZP-31800](https://jira.ez.no/browse/EZP-31800)
| **Type**                                   | bug
| **Target eZ Platform version** | `v3.x`
| **BC breaks**                          | no
| **Tests pass**                          | yes
| **Doc needed**                       | no

#### Checklist:
- [ ] PR description is updated.
- [ ] Tests are implemented.
- [ ] Added code follows Coding Standards (use `$ composer fix-cs`).
- [ ] PR is ready for a review.

### CODE REVIEW

**Review by alongosz — CHANGES_REQUESTED** [review]
I don't understand why you'd want to clear cache of source content type. It should be unchanged after copying, shouldn't it?

**Comment by MarioBlazek** [comment]
But the new content type is not in the listing cache yet. So, if you clear the cache for the new content type, the listing does not refresh.

On the other hand, the new content type is freshly created, why would you want to clear the cache for it?

**Comment by MarioBlazek** [comment]
@alongosz what do you suggest here? Maybe I should load the group of this content type, and then clear the cache for group?

**Comment by alongosz** [comment]
> But the new content type is not in the listing cache yet. So, if you clear the cache for the new content type, the listing does not refresh.
> 
> On the other hand, the new content type is freshly created, why would you want to clear the cache for it?

Both new type and old type are unchanged (the new one has actually cold cache). So the question is what the actual issue is? List not being refreshed? Then rather tags related to list(s) should be invalidated.

This PR misses integration test coverage (`\eZ\Publish\API\Repository\Tests\ContentTypeServiceTest`). Integration test setup takes into the account persistence cache, so the issue you're experiencing should be reproducible. It's gonna be easier to identify what actually we need to invalidate.

Moreover it probably applies to `ezpublish-kernel:7.5` as well, since the issue occurs in API, not UI :-)

**Comment by alongosz** [comment]
Closing in favor of ezsystems/ezpublish-kernel#3069.

**Pull request closed without merging**
